FROM ubuntu

ARG NETHOGS_VERSION=0.8.3
ARG NETHOGS_PKG=nethogs-v$NETHOGS_VERSION.tar.gz
ARG NETHOGS_DIR=nethogs-$NETHOGS_VERSION

RUN mkdir -p /app/tools

WORKDIR /app/tools

RUN apt-get update && \
  apt-get -y install build-essential libncurses5-dev libpcap-dev wget && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN wget -O $NETHOGS_PKG https://github.com/raboof/nethogs/archive/v$NETHOGS_VERSION.tar.gz && \
  tar xvf $NETHOGS_PKG

WORKDIR /app/tools/$NETHOGS_DIR

RUN make && make install && hash -r

CMD ["/usr/local/sbin/nethogs", "-V"]
